### PR TITLE
Update monitorplot ess quantile

### PR DESCRIPTION
**Pull request by OriolAbril**
I have just seen that ess quantile and ess local were not updated some commits ago when removing `z_scale` of binary values.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
@avehtari: Does this change need to percolate through to Stan?

**Comment by OriolAbril** [comment]
@bob-carpenter It is the other way around. In the old version, the boolean values in `ess_tail` and `ess_quantile` were z scaled. This was [corrected in Rstan](https://github.com/stan-dev/rstan/commit/65b5e14df2fae558e2ceba213532525293ab96d5) and then the corrections were [ported back here](https://github.com/avehtari/rhat_ess/commit/bc25dfb6caab78c0331c267502678efa57b13bdc). However, only monitor.R was modified, and not monitorplot.R. Sorry to make you worry.

**Comment by bob-carpenter** [comment]
No worries.  I just try to make sure we don't drop issues on the Stan side.

**Comment by avehtari** [comment]
Thanks @OriolAbril!

**Pull request merged**
